### PR TITLE
notification tweaks

### PR DESCRIPTION
**Pull request by wski**
@clarkjefcoat @rkenyon1969

### CODE REVIEW

**Comment by clarkjefcoat** [comment]
I assume there is an accompanying ozp-center pull request that defines moreNotifications, because now I get a "_this2.props.moreNotifications is not a function" message in the browser console.

:+1:

**Comment by clarkjefcoat** [comment]
Please associate this PR with an issue.

**Comment by rkenyon1969** [comment]
:+1:

**Comment by wski** [comment]
[535](https://github.com/ozone-development/ozp-center/issues/535)

**Pull request merged**
