### PR TITLE
fix(Notifications): Disable notification style when no notification…

### PR DESCRIPTION
**Pull request by wski**
…s are present #282

### CODE REVIEW

**Comment by wski** [comment]
@clarkjefcoat please have a look........................

**Comment by clarkjefcoat** [comment]
I see you changed the title on the pull request.  You also need to change the comment on the commit.

Tested with wski-282 branch of ozp-center.  Test successful.

**Comment by wski** [comment]
rebased

**Comment by clarkjefcoat** [comment]
:+1:

**Comment by arw180** [comment]
:+1:

**Pull request merged**
