### PR TITLE
fix(styling): Add tour css to be accessed by both hud and center

### PR DESCRIPTION
**Pull request by bhalt**

### CODE REVIEW

**Comment by bhalt** [comment]
@rkenyon1969 @wski can you review?

**Comment by rkenyon1969** [comment]
@bhalt @wski 

I got the css in commons.scss running in my hub branch. However, the css needs some tweaking:

screenshot from 2016-06-17 10 47 52

I made a local version in #branch/ozp-hud/app/styles/main.scss (please review):

screenshot from 2016-06-17 10 49 02

**Comment by bhalt** [comment]
@rkenyon1969 Really looking to use one set of CSS in ozp-react-commons rather than separate instances in HUD/Center. Looks like you don't have this ozp-react-commons branch or the latest bootstrap branch pulled into your local code yet?

**Comment by rkenyon1969** [comment]
@bhalt - I've to ozp-react-commons, but not bootstrap. Will install bootstrap and then retest. I agree with central code in commons.scss. Built css in Hud because I didn't want to change your code.

**Comment by rkenyon1969** [comment]
@bhalt  - I'm almost there. I've got ORC and BS up and running. However:

screenshot from 2016-06-17 14 07 46

**Comment by bhalt** [comment]
okay yeah -- something is still messed up with how you're pulling in your instance of ozp-react-commons inside this branch `styling-hudtour` . It may have to be merged in first for it to work correctly? @rkenyon1969

**Comment by rkenyon1969** [comment]
@bhalt - issue resolved:

screenshot from 2016-06-17 16 29 11

Just need to tweak "Welcome to"

**Comment by rkenyon1969** [comment]
:+1:

**Comment by akonsowski** [comment]
it looks fine to me :+1:

**Pull request merged**
