### PR TITLE
chore(styling): Fix link color in notification dropdown

### PR DESCRIPTION
**Pull request by bhalt**
@wski

### CODE REVIEW

**Comment by wski** [comment]
:+1:

**Comment by clarkjefcoat** [comment]
:-1:  Let me know if I've tested this incorrectly, but I still see:

links

**Comment by bhalt** [comment]
Yikes. You're still getting the dropdown scrollbar as well? @wski @clarkjefcoat

**Comment by bhalt** [comment]
@wski @clarkjefcoat check again?

**Comment by clarkjefcoat** [comment]
:+1:

**Comment by akonsowski** [comment]
:+1: looks good to me

**Pull request merged**
