### PR TITLE
Center #345 - Help Desk icon styling updates

### PR DESCRIPTION
**Pull request by sdeighan**

### CODE REVIEW

**Comment by clarkjefcoat** [comment]
:+1:

Tested in IE9,IE11,FF24,Chrome

@blaino - Can you take a look at this?  You will need to run the help-desk branch of ozp-center to see the changes.

**Comment by blaino** [comment]
I've pulled both commons and center help-desk branches and built center against commons. I'm not seeing an icon here. I think I'm doing something wrong. Do I need to pull new icons from somewhere?
screen shot 2015-08-10 at 6 37 36 am

**Comment by blaino** [comment]
From a later PR I see that I need to run npm install to get the new icons. Once I do I see an icon to 'Contact Help Desk'. Now for my next question: what else should I be looking for? Something in the help drop-down?

**Comment by clarkjefcoat** [comment]
Nothing else, you should see "Contact Help Desk" in the dropdown with an icon.

**Comment by blaino** [comment]
Alrighty, then. :+1:

**Comment by arw180** [comment]
Tested. :+1:

**Pull request merged**
